language: swift
osx_image: xcode12.2
sudo: false
env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8
# before_install:
# - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
# - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -version
# - xcodebuild -showsdks
- xcodebuild -workspace LeetCode/LeetCodeSample.xcodeproj -scheme LeetCodeSampleTests
- xcodebuild -workspace LeetCode/LeetCodeSample.xcodeproj -scheme LeetCodeSample 

