language: swift
osx_image: xcode12.2
xcode_project: LeetCode/LeetCodeSample.xcodeproj
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 12
script:
- set -o pipefail
- xcodebuild -project LeetCode/LeetCodeSample.xcodeproj -scheme LeetCodeSample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
