language: swift
osx_image: xcode12.2
cache:
- bundler
sudo: false
env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8
script:
- set -o pipefail
- xcodebuild -project LeetCode/LeetCodeSample.xcodeproj -scheme LeetCodeSample -destination "platform=iOS Simulator,OS=14.2,name=iPhone 12" -sdk iphonesimulator14.1 ONLY_ACTIVE_ARCH=NO test | xcpretty -c
